rasterizer:
	g++ -o rasterizer main.cpp scene.cpp color.cpp tinyxml2.cpp camera.cpp vec3.cpp triangle.cpp translation.cpp scaling.cpp rotation.cpp mesh.cpp helpers.cpp matrix4.cpp vec4.cpp

clean_ex:
	rm -rf ./rasterizer

clean_img:
	rm -rf *.ppm *.png 
